import React from 'react'
import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "../components/providers"
import Nav from '../components/navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rutina',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-bgDarkColor dark:text-white`} >
          <Providers>
            <Nav />
            {children}
          </Providers>
      </body>
    </html>
  )
}
