import Nav from '../components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '../components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`} >
        <Nav />
        <div className="flex">
          <Sidebar />
          <div className="flex-1">{children}</div>
        </div >
      </body>
    </html >
  )
}
